### ISSUE TITLE
how to implement browserHistory.push() in storybook-router?

### ISSUE THREAD

**Issue by SandeshBG** [gvaldambrini/storybook-router#8] opened 2017-07-18 05:05 UTC
I have a react-redux application which on successful login redirects to homepage.This is done using react-router's browserHistory.push("/") .Now I am trying to implement this in react storybook using Story router. 
This browserHistory.push() is placed inside action creator. How can I do this redirection in Storybook router?Currently on successful Login state changes but page doesn't get redirected into homepage.
I use react-router V3.

**Comment by gvaldambrini** [comment] 2017-07-18 07:28
If you want to use the StoryRouter decorator to link between stories you cannot use anything from browserHistory directly (except creating it in the main app entry point). You should be able to use instead the [withRouter wrapper](https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#withroutercomponent-options) or the router context and use the push() and replace() functions whenever you need them.

**Comment by SandeshBG** [comment] 2017-07-18 09:29
How  to redirect withRouter or router context ? In my case the browserHistory.push is called inside action creator.

**Comment by gvaldambrini** [comment] 2017-07-18 09:56
For use the withRouter wrapper you need to define a custom component which will receive as prop the router context, which has all the methods to push/replace/goBack/goForward the history.
You can find [here](https://github.com/gvaldambrini/storybook-router/blob/master/stories/V3/BackForward.js#L15) an example of a custom component which uses withRouter, and you can find in the dedicated [router context documentation](https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#routercontext) how to use it. 
For using those methods inside an action creator you can pass the object to your function or (better imho) you can return a promise and use the method of the router context you want to use within the then.

**Comment by gvaldambrini** [comment] 2017-07-24 21:42
Closing this as it seems there is not a bug behind. Please reopen and provide an example if I'm wrong.

**Closed by gvaldambrini** 2017-07-24 21:42 UTC
