### ISSUE TITLE
Event logging for duplicate routes

### ISSUE THREAD

**Issue by dweldon** [gvaldambrini/storybook-router#12] opened 2017-10-13 00:44 UTC
This is a pretty minor usability bug, but I notice that clicking any two links that resolve to the same path (or clicking the same link twice) will only log the event once. I haven't looked to see if this is intentional in the code, but it does make testing a little harder in some cases (e.g. one component with N links to the same place).

**Comment by gvaldambrini** [comment] 2017-10-14 08:38
Thank you for the report, I imagine you are talking about the vue implementation. 
The current limitation is caused by an implementation detail of the wrapped VueRouter, which aborts every action performed on the same route (and so, does not call the global guard I'm using to perform the logging or the links substitution).  For more details on this topic see this [issue](https://github.com/vuejs/vue-router/issues/1668) or the [Router code](https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L101). 

As the request is perfectly fine with the addon scope I'm working on a workaround to solve the issue, I'll let you know asap.

**Comment by gvaldambrini** [comment] 2017-10-14 12:45
Fixed with version 0.3.1. Closing this, please reopen if you find any issue.

**Closed by gvaldambrini** 2017-10-14 12:45 UTC

**Comment by dweldon** [comment] 2017-10-14 19:56
@gvaldambrini Thanks for the quick fix, and for creating this package!
