### ISSUE TITLE
Fail on hot reload

### ISSUE THREAD

**Issue by eric-burel** [gvaldambrini/storybook-router#24] opened 2018-05-07 13:38 UTC
Hi,
### Which version are you using?
1.0.1
### Are you using storybook-router with a react based project or a vue one?
React
### Please describe the problem:
I get the dreadly `You should not use <Link> outside a <Router>` on hot reload. It does work however if I manually refresh the page. So the decorator seems to be incorrectly applied.

### Please explain how to reproduce the issue or (better) provide an example to do it.
**config.js**
```js
import { configure } from "@storybook/react";
import "./decorators";

const req = require.context("../src", true, /stor(ies|y)\.js$/);

function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```
**decorators.js**
```js
import React from "react";
import { addDecorator } from "@storybook/react";
import StoryRouter from "storybook-react-router";
import "semantic-ui-css/semantic.min.css";

// add
addDecorator(StoryRouter());
```

**Comment by gvaldambrini** [comment] 2018-05-07 20:42
Unfortunately I cannot reproduce the issue from your code. In my setup (and in the provided [examples](https://github.com/gvaldambrini/storybook-router/tree/master/examples/react-router)), everything works fine.
Can you please provide an example repo where I can see the issue?

**Comment by eric-burel** [comment] 2018-05-08 07:04
I'll try to repro indeed. The app is a create-react-app based app, this bug might be related to my context.

**Comment by gvaldambrini** [comment] 2018-05-17 06:35
Any news on this? Please close it if the issue is not related to this package 😄

**Comment by eric-burel** [comment] 2018-05-21 09:42
Sorry I could not repro yet, I am on a project and did not have time sorry. I must check my code to confirm whether the bug is on my side or not but for the moment it sound related either to storybook or to this precise package (otherwise my code would never work, here the bug appears only after a hot reload).

**Comment by gvaldambrini** [comment] 2018-07-16 10:33
As there isn't any progress on this I'm going to close the issue. Feel free to reopen it in case of any news

**Closed by gvaldambrini** 2018-07-16 10:33 UTC
